test = {   'name': 'q1_6',
    'points': 2,
    'suites': [   {   'cases': [   {'code': ">>> popularity_by_year.shape == (9, 2) and popularity_by_year.index.name == 'Year'\nTrue", 'hidden': False, 'locked': False},
                                   {   'code': ">>> set(popularity_by_year.columns) == {'Max_Popularity', 'Median_Popularity'} # This verifies that you have the right column names.\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
