test = {   'name': 'q3_8',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(california_admit_pop, bpd.DataFrame) and california_admit_pop.shape == (33, 6)\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': ">>> set(california_admit_pop.columns) == {'AcceptanceRate', 'Admitted', 'Applied', 'Enrolled', 'Population', 'YieldRate'}\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
